---
title: "fungus"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(vegan)
library(here)
```



```{r cars}
asv_tab_forward = read_csv(here("data/asv_tab_forward_long.csv")) #asv table
asv_tab_unite = read_csv(here("data/asv_unite_forward..csv")) #taxon assignments in same order as OTUs
asv_guilds = read_csv(here("data/asv_unite_forward_ff.guilds.csv")) %>% clean_names() #functional assignments

```

Rarefy to 45316 which is the toka-057-40 depth



```{r}

asv_table = asv_tab_forward %>% 
  select(contains("TOKA")) %>% 
  clean_names(case = "all_caps") %>% 
  select(-TOKA_099_10) %>% 
  t() %>% 
  rrarefy(sample = min(rowSums(.))) %>% 
  t() %>% 
  as.data.frame()



colnames(asv_table) = str_replace_all(colnames(asv_table), "_", "-")


  
  
```


```{r}
asv_table_standard = asv_table %>% 
  t() %>% 
  decostand(method = "total") %>% 
  t() %>% 
  as.data.frame()

asv_table_guilds = asv_table_standard %>% 
  rownames_to_column() %>% 
  left_join(asv_guilds %>% rownames_to_column(), by = "rowname")
  
```

```{r}
fungal_func_sum = asv_table_guilds %>% 
  select(-trait, -sequence, -taxonomy, -taxon, - taxon_level, -notes, -citation_source, - rowname, - guild, -growth_morphology) %>% 
  filter(confidence_ranking %in% c("Probable", "Highly Probable")) %>% 
  select(-confidence_ranking) %>% 
  pivot_longer(-trophic_mode) %>% 
  group_by(name, trophic_mode) %>% 
  summarize(value = sum(value)) %>% 
  pivot_wider(names_from = trophic_mode, values_from = value) %>% 
  column_to_rownames("name")
                 
                 
```

```{r}

asv_all = asv_table_standard %>% 
  t() %>% 
  as.data.frame() %>% 
  select(where(~ any(. != 0)))

asv_10 = asv_table_standard %>% 
  select(ends_with("-10")) %>% 
  t() %>% 
  as.data.frame() %>% 
  select(where(~ any(. != 0)))

asv_40 = asv_table_standard %>% 
  select(ends_with("-40")) %>% 
  t() %>% 
  as.data.frame() %>% 
  select(where(~ any(. != 0)))



```

