---
title: "Gradient analysis finalized"
output: html_document
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(vegan)
library(here)
library(janitor)
library(ggpubr)
library(calecopal)

```

#Soil Data Prep

## Read-in
```{r}
data_nut = tibble(files = list.files(here("data/soil"))) %>%
  mutate(data = map(files, ~ read_csv(here(paste("data/soil/"), .x), 
                                      col_types = cols(`Olsen P` = col_character(),
                                                       `Sodium` = col_double(),
                                                       `Total Nitrogen` = col_double(),
                                                       `pH` = col_double(),
                                                       `Sand` = col_double(),
                                                       `Silt` = col_double(),
                                                       `Clay` = col_double()
                                                       )
                                      )
                    )
         )  

data_rmn_raw = read_csv(here("data/soil/toka_soil_surveys.csv"))

```

## aggregate data
```{r}
# group data
visits_c = data_rmn_raw %>% 
  janitor::clean_names() %>% 
  group_by(point_name, date) %>% 
  select(transect_name, point_name, date, sample_number, carbon_0_10_cm, carbon_10_40_cm, clay_10_40_cm, silt_10_40_cm, sand_10_40_cm, grazed_this_year, bare_ground, litter_depth, catenal_position, starts_with("bulk"), max_depth) %>% 
  nest() %>% 
  ungroup() %>% 
  group_by(point_name) %>% 
  mutate(visit = row_number()) %>%  
  mutate(carbon_0_10 = map_dbl(data, ~ median(.x$carbon_0_10_cm)),
         carbon_10_40 = map_dbl(data, ~ median(.x$carbon_10_40_cm)),
         clay = map_dbl(data, ~ median(.x$clay_10_40_cm)),
         c_change_10 = c(NA, diff(carbon_0_10)),
         c_change_40 = c(NA, diff(carbon_10_40))) %>% 
  ungroup()

#surface points
points_c_surface = visits_c %>% 
  group_by(point_name) %>% 
  mutate(year = lubridate::year(date)) %>% 
  pivot_wider(id_cols = point_name, names_from = year, values_from = carbon_0_10) %>% 
  mutate(change18 = case_when(!is.na(`2015`) ~ `2018`- `2015`,
                              is.na(`2015`) ~ `2018`- `2014`),
         change21 = `2021`- `2018`,
         depth = 10,
         id = paste(point_name, depth, sep = "-"))

#deep points
points_c_depth = visits_c %>% 
  group_by(point_name) %>% 
  mutate(year = lubridate::year(date)) %>% 
  pivot_wider(id_cols = point_name, names_from = year, values_from = carbon_10_40) %>% 
  mutate(change18 = case_when(!is.na(`2015`) ~ `2018`- `2015`,
                              is.na(`2015`) ~ `2018`- `2014`),
         change21 = `2021`- `2018`,
         depth = 40,
         id = paste(point_name, depth, sep = "-"))

#all points
toka_c_points = bind_rows(points_c_surface, points_c_depth) %>% 
  column_to_rownames("id")

```

```{r}
change10 = toka_c_points %>% 
  filter(depth == "10")

change40 = toka_c_points %>% 
  filter(depth == "40")

change10_future = change10 %>% 
  filter(!is.na(change21))

change40_future = change40 %>% 
  filter(!is.na(change21))

```

#16S data prep

## Read-in

```{r}
otu_table = read_table2(here("data/16S/table-w-taxonomy.txt"), skip = 1) %>% 
  select(-`TOKA-099-10`)
braycurtis = read_tsv(here("data/16S/braycurtis.tsv"))
jaccard = read_tsv(here("data/16S/jaccard.tsv"))
shannon = read_tsv(here("data/16S/shannon.tsv"))
```

```{r}

#full otu table

otu_straight = otu_table %>% 
  column_to_rownames("#OTU_ID") %>% 
  select(starts_with("TOKA")) %>% 
  t() %>% 
  as.data.frame() %>% 
  select_if(colSums(.) != 0)

#standardized otu table

otu_standard = decostand(otu_straight, method = "total")
```

```{r}
#key to phyla

phylum_key = otu_table %>% 
  select(`#OTU_ID`, p)

#table of phylum occurence
family_table = otu_straight %>% 
  rownames_to_column("point_id") %>% 
  pivot_longer(-point_id) %>% 
  left_join(phylum_key, by = c("name" = "#OTU_ID")) %>% 
  group_by(point_id, p) %>% 
  mutate(p = str_remove(p, ";")) %>% 
  summarise(family_count = sum(value)) %>% 
  pivot_wider(id_cols = point_id, names_from = p, values_from = family_count)

#standardized family table

family_standard = family_table %>% 
  column_to_rownames("point_id") %>% 
  decostand(method = "total")




```
#Fungal Data Prep

##Read-in
```{r}
asv_tab_forward = read_csv(here("data/asv_tab_forward_long.csv")) #asv table
asv_tab_unite = read_csv(here("data/asv_unite_forward..csv")) #taxon assignments in same order as OTUs
asv_guilds = read_csv(here("data/asv_unite_forward_ff.guilds.csv")) %>% clean_names() #functional assignments
```

```{r}

asv_table = asv_tab_forward %>% 
  select(contains("TOKA")) %>% 
  clean_names(case = "all_caps")

colnames(asv_table) = str_replace_all(colnames(asv_table), "_", "-")

```

```{r}
asv_table_standard = asv_table %>% 
  t() %>% 
  decostand(method = "total") %>% 
  t() %>% 
  as.data.frame()

asv_table_guilds = asv_table_standard %>% 
  rownames_to_column() %>% 
  left_join(asv_guilds %>% rownames_to_column(), by = "rowname")
```

## functional summary
```{r}
fungal_func_sum = asv_table_guilds %>% 
  select(-trait, -sequence, -taxonomy, -taxon, - taxon_level, -notes, -citation_source, - rowname, - guild, -growth_morphology) %>% 
  filter(confidence_ranking %in% c("Probable", "Highly Probable")) %>% 
  select(-confidence_ranking) %>% 
  pivot_longer(-trophic_mode) %>% 
  group_by(name, trophic_mode) %>% 
  summarize(value = sum(value)) %>% 
  pivot_wider(names_from = trophic_mode, values_from = value) %>% 
  column_to_rownames("name")
```

## Divide ASV table into depths
```{r}
asv_all = asv_table_standard %>% 
  t() %>% 
  as.data.frame() %>% 
  select(where(~ any(. != 0)))

asv_10 = asv_table_standard %>% 
  select(ends_with("-10")) %>% 
  t() %>% 
  as.data.frame() %>% 
  select(where(~ any(. != 0)))

asv_40 = asv_table_standard %>% 
  select(ends_with("-40")) %>% 
  t() %>% 
  as.data.frame() %>% 
  select(where(~ any(. != 0)))

```

# Veg data Prep

Read in data    
```{r}
lpi_raw = toka_lpi = read_csv(here("data/veg/toka_lpi.csv"))

lpi_count = lpi_raw %>% 
  janitor::clean_names() %>% 
  filter(!is.na(soil_surface)) %>% 
  group_by(point_id, date) %>% 
  count() %>% 
  mutate(year = year(date))

toka_lpi = lpi_raw %>% 
  janitor::clean_names() %>% 
  filter(!is.na(soil_surface)) %>% 
  mutate(date = lubridate::ymd(date),
         year = lubridate::year(date)) %>% 
  select(point_id, year, top_layer, starts_with("lower")) %>% 
  janitor::remove_empty() %>% 
  pivot_longer(c(top_layer, starts_with("lower")))

toka_canopy = lpi_raw %>% 
  janitor::clean_names() %>% 
  filter(!is.na(soil_surface)) %>% 
  mutate(date = lubridate::ymd(date),
         year = lubridate::year(date)) %>% 
  filter(year != "2016") %>% 
  select(point_id, point_index, direction, year, starts_with("canopy")) %>% 
  janitor::remove_empty() %>% 
  pivot_longer(c(starts_with("canopy")))

```

## Summarize lpi

```{r}

canopy_cover = toka_canopy %>% 
  filter(name == "canopy1",
         ) %>% #!is.na(value)
  group_by(point_id, year)%>% 
  summarise(n = sum(!is.na(value))) %>% 
  left_join(lpi_count, by = c("year", "point_id")) %>% 
  mutate(percent_cover = n.x/n.y) %>% 
  select(point_id, year, percent_cover)

canopy_sum = toka_canopy %>% 
  group_by(point_id, year) %>% 
  count(value) %>% 
  left_join(lpi_count, by = c("year", "point_id")) %>% 
  mutate(percent_cover = n.x/n.y) %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = value, values_from = percent_cover) %>% 
  mutate_all(~ replace_na(.x, 0)) %>% 
  select(-`NA`)
  
  
lpi_sum = toka_lpi %>%   
  group_by(point_id, year) %>% 
  count(value)

com_table = lpi_sum %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = value, values_from = n) %>% 
  mutate_all(~ replace_na(.x, 0)) %>% 
  select(-`NA`, -L, - WL, - NOPLANT)

load(here("data/veg/CAPlantsv2.RData"))

fungrps = CAPlantsv2 %>% 
  janitor::clean_names() %>% 
  select(symbol, fun_grp)

lpi_fun_sum = lpi_sum %>% 
  left_join(fungrps, by = c("value" = "symbol"))


lpi_fun_sum$fun_grp[lpi_fun_sum$value == "2GA"] = "Annual Grass"
lpi_fun_sum$fun_grp[lpi_fun_sum$value == "2FA"] = "Annual Forb"
lpi_fun_sum$fun_grp[lpi_fun_sum$value == "2GP"] = "Perennial Grass"

com_table_fun = lpi_fun_sum %>% 
  group_by(point_id, year, fun_grp) %>% 
  summarise(n = sum(n)) %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = fun_grp, values_from = n) %>% 
  mutate_all(~ replace_na(.x, 0)) %>% 
  select(-`NA`) 


```

## Separate by year and prep for depth
```{r}
data_18 = com_table %>% 
  filter(year == 2018)

data_21 = com_table %>% 
  filter(year == 2021)

data_16 = com_table %>% 
  filter(year == 2016)

data_15 = com_table %>% 
  filter(year == 2014)

points_18 = data_18$point_id

new_com_table = data_18 %>% 
  ungroup() %>% 
  mutate(id = paste(point_id, "10", sep = "-")) %>% 
  column_to_rownames("id") %>% 
  select(-point_id, -year) %>% 
  decostand(method = "total")

new_com_table10 = data_18 %>% 
  ungroup() %>% 
  mutate(id = paste(point_id, "10", sep = "-")) %>% 
  column_to_rownames("id") %>% 
  select(-point_id, -year) %>% 
  decostand(method = "total")

new_com_table40 = data_18 %>% 
  ungroup() %>% 
  mutate(id = paste(point_id, "40", sep = "-")) %>% 
  column_to_rownames("id") %>% 
  select(-point_id, -year) %>% 
  decostand(method = "total")


```




```{r}
com_change_table18 = com_table %>% 
  filter(year == 2018 | year < 2018) %>% 
  group_by(point_id) %>% 
  filter(n() > 1) %>% 
  mutate(id = paste(point_id, year, sep = "-")) %>% 
  column_to_rownames("id") %>% 
  ungroup() %>% 
  select(-point_id, - year) %>% 
  decostand(method = "total")

year_dist18 = vegdist(com_change_table18, method = "bray") %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  filter(str_detect(rowname, "2016")) %>% 
  column_to_rownames("rowname") %>% 
  select(contains("2018")) %>% 
  as.matrix()

veg_point_distance18 = data_frame(distance = diag(year_dist18)) %>% 
  mutate(points = rownames(year_dist18))
```
## Summarize community change

```{r}

com_change_table = com_table %>% 
  filter(year == 2018 | year == 2021) %>% 
  group_by(point_id) %>% 
  filter(n() > 1) %>% 
  mutate(id = paste(point_id, year, sep = "-")) %>% 
  column_to_rownames("id") %>% 
  ungroup() %>% 
  select(-point_id, - year) %>% 
  decostand(method = "total")

year_dist = vegdist(com_change_table, method = "bray") %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  rownames_to_column() %>% 
  filter(str_detect(rowname, "2018")) %>% 
  column_to_rownames("rowname") %>% 
  select(contains("2021")) %>% 
  as.matrix()

veg_point_distance = data_frame(distance = diag(year_dist)) %>% 
  mutate(points = rownames(year_dist))

```

```{r}
top_species = new_com_table %>% 
  rownames_to_column() %>% 
  pivot_longer(-rowname) %>% 
  group_by(name) %>% 
  summarise(total = sum(value))
```

```{r}
com_table21_change = data_21 %>% 
  column_to_rownames("point_id") %>% 
  select(-year) %>% 
  decostand(method = "total")

com_table18_change = data_18 %>% 
  column_to_rownames("point_id") %>% 
  select(-year) %>% 
  decostand(method = "total") %>% 
  filter(rownames(.) %in% rownames(com_table21_change))

veg_change_com = com_table21_change - com_table18_change

````




#Bacterial Analyses

```{r}

otu_standard_match10 = otu_standard %>% 
  filter(rownames(.) %in% rownames(change_data10)) %>% 
  as.data.frame()

otu_standard_match40 = otu_standard %>% 
  filter(rownames(.) %in% rownames(change_data40)) %>% 
  as.data.frame()

```


## All 16S
```{r}
NMS16S = metaMDS(otu_standard_match, distance = "bray", k = 2, maxit = 999, trymax = 500, wascores = TRUE, autotransform = FALSE)
```
















