---
title: "soil_data_cleanup"
author: "Jacob Weverka"
date: "7/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
```

Read in the data

```{r}

data_nut = tibble(files = list.files(here("data/soil"))) %>%
  mutate(data = map(files, ~ read_csv(here(paste("data/soil/"), .x), 
                                      col_types = cols(`Olsen P` = col_character(),
                                                       `Sodium` = col_double(),
                                                       `Total Nitrogen` = col_double(),
                                                       `pH` = col_double(),
                                                       `Sand` = col_double(),
                                                       `Silt` = col_double(),
                                                       `Clay` = col_double()
                                                       )
                                      )
                    )
         )  

data_rmn_raw = read_csv(here("data/soil/toka_soil_surveys.csv"))


```


```{r}
soil_grouped = data_rmn_raw %>% 
  janitor::clean_names() %>% 
  group_by(point_name, date) %>% 
  select(transect_name, point_name, date, sample_number, carbon_0_10_cm, carbon_10_40_cm, clay_10_40_cm, silt_10_40_cm, sand_10_40_cm, grazed_this_year, bare_ground, litter_depth, catenal_position, starts_with("bulk"), max_depth) %>% 
  nest()

soil_visits = soil_grouped %>% 
  ungroup() %>% 
  group_by(point_name) %>% 
  mutate(visit = row_number()) 
# 
# %>% 
#   filter(n() == 3)

visits_c = soil_visits %>% 
  mutate(carbon_0_10 = map_dbl(data, ~ median(.x$carbon_0_10_cm)),
         carbon_10_40 = map_dbl(data, ~ median(.x$carbon_10_40_cm)),
         clay = map_dbl(data, ~ median(.x$clay_10_40_cm)),
         c_change_10 = c(NA, diff(carbon_0_10)),
         c_change_40 = c(NA, diff(carbon_10_40))) %>% 
  ungroup()


points_c_surface = visits_c %>% 
  group_by(point_name) %>% 
  mutate(year = lubridate::year(date)) %>% 
  pivot_wider(id_cols = point_name, names_from = year, values_from = carbon_0_10) %>% 
  mutate(change18 = case_when(!is.na(`2015`) ~ `2018`- `2015`,
                              is.na(`2015`) ~ `2018`- `2014`),
         change21 = `2021`- `2018`,
         depth = 10,
         id = paste(point_name, depth, sep = "-"))


points_c_depth = visits_c %>% 
  group_by(point_name) %>% 
  mutate(year = lubridate::year(date)) %>% 
  pivot_wider(id_cols = point_name, names_from = year, values_from = carbon_10_40) %>% 
  mutate(change18 = case_when(!is.na(`2015`) ~ `2018`- `2015`,
                              is.na(`2015`) ~ `2018`- `2014`),
         change21 = `2021`- `2018`,
         depth = 40,
         id = paste(point_name, depth, sep = "-"))

toka_c_points = bind_rows(points_c_surface, points_c_depth) %>% 
  column_to_rownames("id")


```




```{r}
all_data = data_nut %>% 
  unnest(data) %>%
  janitor::clean_names() %>% 
  mutate(collect_date = lubridate::dmy(collect_date),
         collect_date1 = lubridate::mdy(collect_date_1_rmn_metrics),
         date = case_when(!is.na(collect_date) ~ collect_date,
                          !is.na(collect_date1) ~ collect_date1
                          ),
         year = lubridate::year(date)
  ) %>% 
  filter(!is.na(date)) %>% 
  select(files, depth_cm, year, point_id, date, olsen_p, sand, silt, clay, texture, p_h, cec, calcium, magnesium, potassium, sodium, total_org_carbon, total_nitrogen, total_nitrogen_2)
  
```



```{r}
d = all_data %>% 
  nest(-files, -depth_cm, -year) %>% 
  select(-files) %>% 
  pivot_wider(id_cols = depth_cm, names_from = year, values_from = data) %>% 
  mutate(`2015` = map2(`2015`, `2018`, ~ .x %>% 
                         filter(point_id %in% .y$point_id) %>% 
                         rename(nitrogen = total_nitrogen) %>% 
                         mutate(cn = total_org_carbon/nitrogen)),
         `2018` = map2(`2018`, `2015`, ~ .x %>% 
                         filter(point_id %in% .y$point_id) %>% 
                         rename(nitrogen = total_nitrogen_2)%>% 
                         mutate(cn = total_org_carbon/nitrogen))
         ) %>% 
  mutate(change = map2(`2018`, `2015`, ~ .x %>% 
                         full_join(.y, by = c("point_id"), suffix = c("2018", "2015")) %>% 
                         select(contains(c("point_id", "sand", "silt", "clay", "total_org", "nitrogen", "cn"))) %>% 
                          mutate(c_change = total_org_carbon2018 - total_org_carbon2015,
                                c_pc_change = c_change/total_org_carbon2015,
                                n_change = nitrogen2018 - nitrogen2015,
                                cn_change = cn2018 - cn2015,
                                c_2018 = total_org_carbon2018,
                                n_2018 = nitrogen2018,
                                c_n_ratio = c_2018/n_2018,
                                sand = sand2018,
                                silt = silt2018,
                                clay = clay2018
                                ) %>% 
                         select(point_id, n_change, n_2018, sand, silt, clay, contains("nitrogen")) 
                         )
         )
                       
                         
                         
                         
                         # 
                         # mutate(c_change = .x$total_org_carbon - .y$total_org_carbon,
                         #        c_pc_change = (.x$total_org_carbon - .y$total_org_carbon)/.y$total_org_carbon,
                         #        n_change = .x$nitrogen - .y$nitrogen,
                         #        cn_change = .x$cn - .y$cn,
                         #        c_2018 = .x$total_org_carbon,
                         #        n_2018 = .x$nitrogen,
                         #        c_n_ratio = c_2018/n_2018)))
```
```{r}
change = d %>% 
  select(depth_cm, change) %>% 
  unnest(change) %>% 
  mutate(depth = case_when(depth_cm == "0 to 10" ~ 10,
                           depth_cm == "10 to 40" ~ 40)) %>% 
  left_join(toka_c_points, by = c("point_id" = "point_name", "depth")) %>% 
  mutate(c_n_ratio = `2018`/n_2018,
         c_n_15 = `2015`/nitrogen2015,
         cn_change = c_n_ratio - c_n_15)
# 
# ggplot(change, aes(x = c_change)) +
#   geom_histogram() +
#   facet_wrap(.~ depth_cm)
# 
# ggplot(change, aes(x = n_change)) +
#   geom_histogram() +
#   facet_wrap(.~ depth_cm)
# 
# ggplot(change, aes(x = cn_change)) +
#   geom_histogram() +
#   facet_wrap(.~ depth_cm)
# 
# ggplot(change, aes(x = n_change, y = c_change, color = depth_cm)) +
#   geom_point()
# 
# ggplot(change, aes(x = c_pc_change, color = depth_cm)) +
#   geom_histogram()+
#   facet_wrap(.~ depth_cm)
# 
# ggplot(change, aes(x = c_change, y = cn_change, color = depth_cm)) +
#   geom_point()

```
```{r}
change10 = change %>% 
  filter(depth_cm == "0 to 10")

change40 = change %>% 
  filter(depth_cm == "10 to 40")
summary(change40)
```

```{r}
# m = lm(c_change ~ n_change, data = change)
# summary(m)
```

