---
title: "veg_data_cleanup"
author: "Jacob Weverka"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(vegan)
library(lubridate)
```

Read in data    
```{r}

veg = read_csv(here("data/veg/TOKA_RMNData_2018_RMN_Plants.csv"), skip = 3, col_types = cols(`Annual Forb` = col_double())) %>% 
  janitor::clean_names() %>% 
  drop_na(annual_forb)

newveg = veg[,-1]
points = veg[,1]

```


```{r}
lpi_raw = toka_lpi = read_csv(here("data/veg/toka_lpi.csv"))

lpi_count = toka_lpi = read_csv(here("data/veg/toka_lpi.csv")) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(soil_surface)) %>% 
  group_by(point_id, date) %>% 
  count() %>% 
  mutate(year = year(date))

toka_lpi = read_csv(here("data/veg/toka_lpi.csv")) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(soil_surface)) %>% 
  mutate(date = lubridate::ymd(date),
         year = lubridate::year(date)) %>% 
  select(point_id, year, top_layer, starts_with("lower")) %>% 
  janitor::remove_empty() %>% 
  pivot_longer(c(top_layer, starts_with("lower")))

toka_canopy = read_csv(here("data/veg/toka_lpi.csv")) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(soil_surface)) %>% 
  mutate(date = lubridate::ymd(date),
         year = lubridate::year(date)) %>% 
  select(point_id, point_index, direction, year, starts_with("canopy")) %>% 
  janitor::remove_empty() %>% 
  filter(year == 2018) %>% 
  pivot_longer(c(starts_with("canopy")))

canopy_cover = toka_canopy %>% 
  filter(name == "canopy1",
         !is.na(value)) %>% 
  group_by(point_id, year) %>% 
  count() %>% 
  left_join(lpi_count, by = c("year", "point_id")) %>% 
  mutate(percent_cover = n.x/n.y) %>% 
  select(point_id, year, percent_cover)

canopy_sum = toka_canopy %>% 
  group_by(point_id, year) %>% 
  count(value) %>% 
  filter(!is.na(value)) %>% 
  left_join(lpi_count, by = c("year", "point_id")) %>% 
  mutate(percent_cover = n.x/n.y) %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = value, values_from = percent_cover) %>% 
  mutate_all(~ replace_na(.x, 0))
  
  
  
lpi_sum = toka_lpi %>%   
  group_by(point_id, year) %>% 
  count(value)

com_table = lpi_sum %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = value, values_from = n) %>% 
  mutate_all(~ replace_na(.x, 0)) %>% 
  select(-`NA`, -L, - WL, - NOPLANT) %>% 
  filter(point_id != "TOKA-013",
         point_id != "TOKA-006")

load(here("data/veg/CAPlantsv2.RData"))

fungrps = CAPlantsv2 %>% 
  janitor::clean_names() %>% 
  select(symbol, fun_grp)

lpi_fun_sum = lpi_sum %>% 
  left_join(fungrps, by = c("value" = "symbol"))


lpi_fun_sum$fun_grp[lpi_fun_sum$value == "2GA"] = "Annual Grass"
lpi_fun_sum$fun_grp[lpi_fun_sum$value == "2FA"] = "Annual Forb"
lpi_fun_sum$fun_grp[lpi_fun_sum$value == "2GP"] = "Perennial Grass"

lpi_fun = lpi_fun_sum %>% 
  group_by(point_id, year, fun_grp) %>% 
  summarise(n = sum(n))

com_table_fun = lpi_fun %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = fun_grp, values_from = n) %>% 
  mutate_all(~ replace_na(.x, 0)) %>% 
  select(-`NA`) 

```

```{r}
releve = read_csv(here("data/veg/toka_releve.csv")) %>% 
  clean_names()

woody_cover = releve %>% 
  filter(vegetation_type == "trees" | vegetation_type == "shrubs") %>% 
  mutate(year = year(event_date)) %>% 
  select(point_id, vegetation_type, usda_code, year, percent_cover) %>% 
  group_by(point_id, year, usda_code) %>% 
  summarise(percent_cover = sum(percent_cover)) %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = usda_code, values_from = percent_cover) %>% 
  mutate_all(~ replace_na(.x, 0))

woody_total = releve %>% 
  filter(vegetation_type == "trees" | vegetation_type == "shrubs") %>% 
  mutate(year = year(event_date)) %>% 
  select(point_id, vegetation_type, usda_code, year, percent_cover) %>% 
  group_by(point_id, year) %>% 
  summarise(percent_cover = sum(percent_cover))

tree_cover = releve %>% 
  filter(vegetation_type == "trees") %>% 
  mutate(year = year(event_date)) %>% 
  select(point_id, vegetation_type, usda_code, year, percent_cover) %>% 
  group_by(point_id, year, usda_code) %>% 
  summarise(percent_cover = sum(percent_cover)) %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = usda_code, values_from = percent_cover) %>% 
  mutate_all(~ replace_na(.x, 0))

tree_total = releve %>% 
  filter(vegetation_type == "trees") %>% 
  mutate(year = year(event_date)) %>% 
  select(point_id, vegetation_type, usda_code, year, percent_cover) %>% 
  group_by(point_id, year) %>% 
  summarise(percent_cover = sum(percent_cover))
  

shrub_cover = releve %>% 
  filter( vegetation_type == "shrubs") %>% 
  mutate(year = year(event_date)) %>% 
  select(point_id, vegetation_type, usda_code, year, percent_cover) %>% 
  group_by(point_id, year, usda_code) %>% 
  summarise(percent_cover = sum(percent_cover)) %>% 
  pivot_wider(id_cols = c(point_id, year), names_from = usda_code, values_from = percent_cover) %>% 
  mutate_all(~ replace_na(.x, 0))

shrub_total = releve %>% 
  filter(vegetation_type == "shrub") %>% 
  mutate(year = year(event_date)) %>% 
  select(point_id, vegetation_type, usda_code, year, percent_cover) %>% 
  group_by(point_id, year) %>% 
  summarise(percent_cover = sum(percent_cover))

```






```{r}
my.rda = rda(newveg)


```
```{r}
# knitr::knit(here("code/soil_data_cleanup.Rmd"))
```
Generate the PCA
```{r}
data_18 = com_table %>% 
  filter(year == 2018)

points_18 = data_18$point_id

new_com_table = data_18 %>% 
  ungroup() %>% 
  mutate(id = paste(point_id, "10", sep = "-")) %>% 
  column_to_rownames("id") %>% 
  select(-point_id, -year) %>% 
  decostand(method = "normalize")

new_com_table10 = data_18 %>% 
  ungroup() %>% 
  mutate(id = paste(point_id, "10", sep = "-")) %>% 
  column_to_rownames("id") %>% 
  select(-point_id, -year) %>% 
  decostand(method = "normalize")

new_com_table40 = data_18 %>% 
  ungroup() %>% 
  mutate(id = paste(point_id, "40", sep = "-")) %>% 
  column_to_rownames("id") %>% 
  select(-point_id, -year) %>% 
  decostand(method = "normalize")

com.rda = rda(new_com_table)
com_scores = scores(com.rda, display = "sites", choices = c(1,2,3,4)) %>% 
  as.data.frame() %>% 
  add_column(point_id = points_18) %>% 
  left_join(change, by = "point_id")

com_surface = com_scores %>% 
  filter(depth_cm == "0 to 10")

com_depth = com_scores %>% 
  filter(depth_cm == "10 to 40")

com_vect = scores(com.rda, display = "species", choices = c(1,2,3)) %>% 
  as.data.frame() %>% 
  mutate(mag = sqrt(PC1^2 + PC2^2))

top_com = com_vect %>% 
  slice_max(n = 10, order_by = mag)

ggplot(z, aes(x = PC1, y = PC2)) +
  geom_smooth(method = "lm") +
  geom_point(aes(color = cn_change), size = 3) +
  geom_segment(data = com_vect, aes (x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm"))) +
  geom_text(data = top_com, aes(x = PC1, y = PC2, label = rownames(top_com)))
```
Do PCA axes correlate to C change or to C status in surface soils?
```{r}
#drop outlier
z = com_surface %>% 
  filter(point_id != "TOKA-089")

#including outlier - change
m_change = lm(c_change ~ PC1 + PC2 + PC3, data = com_surface)
summary(m_change)
plot(m_change)

#including outlier - status
m_status = lm(c_2018 ~ PC1 + PC2 + PC3, data = com_surface)
summary(m_status)

```

```{r}
# cca(new_com_table ~ c_change + c_2018, data = com_surface)
# cca(new_com_table ~ c_change + c_2018, data = com_depth)
# 
# ca = cca(new_com_table ~ com_surface$c_change + com_surface$c_2018 + com_depth$c_change + com_depth$c_2018)
# anova(ca)

```

Same question, but with deep soils
```{r}
# #including outlier - change
# m_change = lm(c_change ~ PC1 + PC2 + PC3, data = com_depth)
# summary(m_change)
# plot(m_change)
# 
# #including outlier - status
# m_status = lm(c_2018 ~ PC1 + PC2 + PC3, data = com_depth)
# summary(m_status)
# plot(m_status)
```


```{r}

# veg_st = decostand(newveg, "total")
# st_PCA = rda(veg_st)
# veg_scores = scores(st_PCA, display = "sites") %>% 
#   as.data.frame() %>% 
#   add_column(points) %>% 
#   left_join(change, by = "point_id")
# 
# PCAvect = scores(st_PCA, display = "species") %>% 
#   as.data.frame()
# 


```





```{r}
surface = veg_scores %>% 
  filter(depth_cm == "0 to 10")

depth = veg_scores %>% 
  filter(depth_cm == "10 to 40")

# ggplot(surface, aes(x = PC1, y = PC2)) +
#   geom_point(aes(color = cn_change), size = 2) +
#   geom_segment(data = PCAvect, aes (x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm"))) +
#   geom_text(data = PCAvect, aes(x = PC1, y = PC2, label = rownames(PCAvect))) + 
#   scale_color_viridis_c()
# 
# ggplot(depth, aes(x = PC1, y = PC2)) +
#   geom_point(aes(color = cn_change), size = 2) +
#   geom_segment(data = PCAvect, aes (x = 0, y = 0, xend = PC1, yend = PC2), arrow = arrow(length = unit(0.2, "cm"))) +
#   geom_text(data = PCAvect, aes(x = PC1, y = PC2, label = rownames(PCAvect))) + 
#   scale_color_brewer(palette = "RdBu") + 
#   scale_color_viridis_c()
```
```{r}

# m1 = lm(c_pc_change ~ PC1 + PC2, data = surface)
# summary(m1)
# 
# m2 = lm(c_pc_change ~ PC1 + PC2 + clay, data = depth)
# summary(m2)
```


